@startuml タスク管理
title タスク管理
left to right direction
actor グループのホスト
actor グループの参加者

rectangle {
    グループのホスト --> (タスク管理したいグループを選択する)
    グループのホスト --> (タスク一覧を閲覧する)
    グループのホスト --> (タスクを作成する)
    グループのホスト --> (子タスクを作成する)
    グループのホスト --> (タスクを終了する)
    グループのホスト --> (タスクを削除する)
    グループのホスト --> (タスクを編集する)
    (タスク管理したいグループを選択する) <-- グループの参加者
    (タスク一覧を閲覧する) <-- グループの参加者
    (タスクを終了する) <-- グループの参加者
    (タスクを編集する) <-- グループの参加者
}
@enduml