@startuml タスク集約

title タスク集約

package "タスク集約(TaskAggregation)" {
    class Task << (R,red) RootEntity >> {
        taskId: TaskId
        groupId: GroupId
        taskAssignee タスク担当者: TaskAssignee
        taskName: TaskName
        taskStatus: TaskStatus
        taskProgressRate: TaskProgressRate
        taskDeadline: TaskDeadline
        taskOverview タスクの概要: TaskOverview
        parentTaskId 親タスクのID: TaskId|null
    }

    class TaskId {
        - value: string
    }

    class TaskAssignee {
        - value: string
    }

    class TaskName {
        -value: string
    }

    class TaskStatus {
        - value: Enum { notStarted(未着手), ongoing(進行中), finished(終了済み)}
    }

    class TaskProgressRate {
        - value: int
    }

    class TaskDeadline {
        - value: DateTime
    }

    class TaskOverview {
        - value: string
    }

    note bottom of Task
        ・タスクの作成はそのタスクを持っているグループのホストユーザーしか行えない
        ・タスクの編集は、そのグループホストユーザーかタスクの担当者しか行えない
        ・タスクの下に子タスクを作成できる
        ・親タスクの持っている子タスクのTaskStatusが全て「終了済み」になったら
        　自動的に親タスクのTaskStatusも「終了済み」にする
        ・親タスクの持っている子タスクの中のどれか一つでもTaskStatusが「終了済み」以外の場合に
        　もし親タスクのTaskStatusが「終了済み」だったら、TaskStatusを「進行中」に戻す
        ・グループが削除されたら、そのグループが持っているタスクも削除する
    end note

    note bottom of TaskId
        TaskIdはULIDなどの時系列ソート可能なIDを用いる
    end note

    note bottom of TaskAssignee
        ・TaskAssigneeはidentityManagementコンテキストから取得したUserIdを設定する
        ・担当者なしも設定できるようにする
    end note

    note bottom of TaskName
        - 1文字以上50文字以内の文字列
        - 空文字列での登録は行えない
    end note

    note bottom of TaskStatus
        未着手、進行中、終了済みがある
    end note

    note bottom of TaskProgressRate
        ・0 ~ 100%まである
        ・100%になったら自動的にTaskStatusを「終了済み」にする
    end note

    note bottom of TaskDeadline
        過去の日付は設定できない
    end note

    note bottom of TaskOverview
        2000文字まで
    end note

    Task *-down- TaskId
    Task -down-> userInformation.GroupId
    Task *-down- TaskAssignee
    Task *-down- TaskName
    Task *-down- TaskStatus
    Task *-down- TaskProgressRate
    Task *-down- TaskDeadline
    Task *-down- TaskOverview
}

@enduml