@startuml ユーザー情報

title ユーザー情報

package "ユーザー情報(userInformation)" {
    class UserInformation {
        userId: UserId
        userName: string
        participatingGroupList 参加しているグループ一覧: ParticipatingGroupList
        ownGroupList 所有しているグループ一覧: OwnGroupList
    }

    class UserId {
        - value: string
    }

    class ParticipatingGroupList {
        - groupIdList: GroupId[]
    }

    class OwnGroupList {
        - groupIdList: GourpId[]
    }

    class GroupId {
        - value: string
    }

    note bottom of UserInformation
        identityManagementコンテキストから取得したデータをこのクラスに設定する
    end note

    note bottom of UserId
        identityManagementコンテキストから取得したUserIdを設定する
    end note

    note bottom of GroupId
        identityManagementコンテキストから取得したGroupIdを設定する
    end note

    UserInformation *-down- UserId
    UserInformation *-down- ParticipatingGroupList
    UserInformation *-down- OwnGroupList
    ParticipatingGroupList "1" *-down- "0..n" GroupId
    OwnGroupList "1" *-down- "0..n" GroupId
}

@endumkl